### PR TITLE
Add github action test for code style

### LINKED ISSUE #488: Create github action for code style checking
Depends on #486

### PR DESCRIPTION
**Pull request by bjrne**
Depends on #495 
Closes #488

### CODE REVIEW

**Comment by Baschdl** [comment]
What kind of environment is installed? Can we cache it?

**Comment by bjrne** [comment]
Yes, on ubuntu it clones all necessary repositories into `~/.cache/pre-commit/`. Can we cache that?

**Comment by bjrne** [comment]
```yaml
- name: set PY
  run: echo "::set-env name=PY::$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')"
- uses: actions/cache@v1
  with:
    path: ~/.cache/pre-commit
    key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml', '.flake8', '.isort.cfg') }}
- uses: pre-commit/action@v1.0.1
```
The cache name is proposed [here](https://github.com/pre-commit/action#using-this-action), in the pre-commit github example action. I am not sure whether we really need it, the hashed yaml file should be enough I think.

Do we also need restore keys?

**Comment by bjrne** [comment]
Ready when #495 is merged.

**Review by Baschdl — APPROVED** [review]
image
Works and looks good

**Pull request merged**
