### PR TITLE
fix PLZs in AT

### LINKED ISSUE #227: ZIP / postal codes displayed at wrong location on map
https://match4healthcare.slack.com/archives/C010K4T5YGZ/p1585326080060500
Grundsätzlich passt jetzt die Validierung der PLZ. Dafür haben wir gelernt, dass diese in AT nicht eindeutig sind. D.h. Innsbruck oder Graz als Landeshauptstädte haben die gleiche wie ein Kuhkaff daneben. Und natürlich zeigen wir den Kreis jetzt am Kuhkaff an. 

Müssen wir mal schauen wie das lösbar ist. Aber im worst case sind die Kreise ein paar km off, also nicht superkritisch. 

image
image

### PR DESCRIPTION
**Pull request by josauder**
closes #227

### CODE REVIEW

**Review by bjrne — APPROVED** [review]
Works like a charm locally. Beautiful! :rose:

**Comment by rth** [comment]
pgeocode maintainer here, if you encounter any issues with the library of the accuracy of the postal code data don't hesitate to ping me.

**Comment by Baschdl** [comment]
@rth Yes, we currently merge two different sources for postal codes to get all existing codes. But we didn't check if the first source has invalid postal codes and only those are not included in the data of pgeocode. @josauder can tell you more about that.

**Comment by rth** [comment]
> Yes, we currently merge two different sources for postal codes to get all existing codes. But we didn't check if the first source has invalid postal codes and only those are not included in the data of pgeocode. @josauder can tell you more about that.

Good to know. Could you please open a separate issue about it  in this repo? Thanks!

**Comment by rth** [comment]
Opened https://github.com/helping-health/match4healthcare/issues/330

**Pull request merged**
