### PR TITLE
Add utilities for creating fake data

### LINKED ISSUE #465: Create new dev-Fixtures
Create new fixtures for quick setup of dev systems
Include sample users and the following validated and approved users with username = password and e-mails set to something random:

- supporter
- facility
- staff
- superuser

### PR DESCRIPTION
**Pull request by feeds**
Closes #465 

Maybe more advanced data creation strategies would be nice, but I will open a new issue for that

### CODE REVIEW

**Comment by feeds** [comment]
@bjrne why is the plz list formatted to so many lines? :D

**Comment by bjrne** [comment]
This file is manually excluded from automatic formatting due to this. Please change the path in .pre-commit-donfig.yaml ;)

**Comment by Baschdl** [comment]
Side effect on travis, last commit works: https://travis-ci.org/github/match4everyone/match4healthcare/builds/684319052

**Comment by feeds** [comment]
@bjrne the intended behaviour now is that you can use all parameters at the same time. Delete will always be executed first. That way you can clean first and add new users with only one command :)

**Review by bjrne — APPROVED** [review]
Lots of potential for more useful data, but nice to have it as a manage.py function :)

**Pull request merged**
