### PR TITLE
Add github action labelling draft pull requests as PR:wip

### PR DESCRIPTION
**Pull request by Baschdl**
To test this, something has to actually change in the repository.
Using actions/labeler@v2 is a bit hacky but works.

### CODE REVIEW

**Review by feeds — CHANGES_REQUESTED** [review]
We should also add the `PR:ready-for-merge` tag when the draft ist changed to a pull request via the action
`ready_for_review`

**Comment by bjrne** [comment]
What happens when a review requesting changes is submitted? Will the action react?

Also, why did you change the readme here?

**Comment by Baschdl** [comment]
Needed some changes to test it.

> What happens when a review requesting changes is submitted? Will the action react?

No

**Comment by Baschdl** [comment]
Should we just do it manually or is that important for someone and worth investing the time?

**Comment by Baschdl** [comment]
Shouldn't be too complicated after understanding the github actions finally

**Pull request closed without merging**
