### PR TITLE
Email validation better error

### PR DESCRIPTION
**Pull request by josauder**
Now gives "Email already taken" in form rather than throwing internal server error

### CODE REVIEW

**Review by Baschdl — CHANGES_REQUESTED** [review]
Did you not implement this for the hospital form on purpose?

**Comment by Baschdl** [comment]
Ah. The unique on the hospital mail column is missing, isn't it?

**Review by Baschdl — APPROVED** [review]

**Comment by Baschdl** [comment]
Merge for organization of apps. Should be discussed nevertheless.

**Comment by josauder** [comment]
Unique mail for hospitals is enforced in the User table. Hospital has a duplicate email field (see https://github.com/Baschdl/match4healthcare/issues/72)

**Pull request merged**
