### PR TITLE
Add example env files to prevent merge conflicts with local changes

### PR DESCRIPTION
**Pull request by Baschdl**
- [ ] **Test locally if files are removed with this PR before deploying on server**

### CODE REVIEW

**Comment by Baschdl** [comment]
My local behavior suggests that it indeed deletes the previous entries

**Comment by kevihiiin** [comment]
How about removing the files like here (keeps local files):
https://stackoverflow.com/a/1143800
And then create "new" sample files
- - - - - -
Edit: Apparently that does not work for remote repositories

**Comment by Baschdl** [comment]
Backup files are created on production and staging

**Review by kevihiiin — APPROVED** [review]
Looks good to me

**Pull request merged**
