### PR TITLE
Release 1.1

### LINKED ISSUE #253: No static files in production docker
**Problem**: No static file is being served when the containers are build new (e.g. new system or docker system prune)

**Workaround**: Toggle the debug option in the setings file

**Investigate**: Check logs acessing the site in travis for all branches.

### LINKED ISSUE #254: Staticfile error in deployment
When deploying, a staticfile error is thrown which is fixed by DEBUG=FALSE --> DEBUG=TRUE --> DEBUG=FALSE

### PR DESCRIPTION
**Pull request by kevihiiin**
Added many fixes and new design

### CODE REVIEW

**Comment by kevihiiin** [comment]
Recheck all merged braches with Travis, first call page and then grep error log size.

**Comment by Baschdl** [comment]
@kevihiiin What are you saying?

**Comment by kevihiiin** [comment]
We should add additioinal tests to travis to accommodate for errors thrown by the backend. After we found the source for this weird static file issue, I think it is save to merge.

**Comment by kevihiiin** [comment]
No inherrent issues with the code, just the order of executed commands in deployment. 
After collecting static files, the backend container needs to be restarted.

**Review by Baschdl — APPROVED** [review]

**Pull request merged**
